# Jekyll configuration

name: wrathematics
description: My Stack Overfloweth

# Url is currently only used only for the RSS feed in feed.xml
url: https://wrathematics.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
# baseurl: ''

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: true

social:
  github: wrathematics
  #stackoverflow: ''
  linkedin: schmidtdrew
  #instagram: ''
  #lastfm: ''
  twitter: wrathematics
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-85667586-1

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: librestats
comments: true

permalinks: 
  oldblogstyle: '/:year/:month/:day/:title/'
  other: '/:name'

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false

exclude: ['README.md', 'LICENSE']
include: ['_pages']
